# Generated by Django 4.0.4 on 2022-06-03 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_order_id_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='popularity',
            new_name='score',
        ),
    ]
