# Generated by Django 4.0.4 on 2022-06-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productorder_alter_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='quantity',
            new_name='qty',
        ),
    ]
